

platform :ios, ‘9.0’

use_frameworks!

target 'TSUIKit' do

# pod 'TFKit',:git=>'/Users/threestonewang/Desktop/TFKit'
#pod 'TS_UIKit',:git=>'https://github.com/StoneStoneStoneWang/TSUIKit.git'

pod 'JXTAlertManager'

pod 'SVProgressHUD'

pod 'MJRefresh'
end
