

platform :ios, ‘9.0’

use_frameworks!

target 'TSUIKit' do

# pod 'TFKit',:git=>'/Users/threestonewang/Desktop/TFKit'
pod 'TS_UIKit',:git=>'https://github.com/StoneStoneStoneWang/TS_UIKit.git'


end
